%% 设置训练参数

trainOpts = rlTrainingOptions(...
    'MaxEpisodes', 10000, ...
    'MaxStepsPerEpisode', 500, ...
    'Verbose', false, ...
    'Plots','training-progress',...
    'StopTrainingCriteria','AverageReward',...
    'StopTrainingValue',480); 




%% 训练
trainingStats = train(agent,env,trainOpts);